name: demo
on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main     
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: print name
        run: |
          echo "my name is krishna"
          echo "i am working in ntt data"
